# Generated by Django 4.2.3 on 2023-08-08 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100, verbose_name='firstName')),
                ('lastName', models.CharField(max_length=100, verbose_name='lastName')),
                ('comment', models.TextField(verbose_name='Comment')),
            ],
            options={
                'permissions': [('contact_yes', 'contactyes')],
            },
        ),
    ]
