# Generated by Django 4.2.3 on 2023-08-08 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('user_yes', 'useryes')], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
