# Generated by Django 4.2.3 on 2023-08-08 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['first_name'], 'permissions': [('user_yes', 'useryes')], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
